heroImage: /images/hero-zerog-research.jpg
heroTitle: Low-Gravity Fluids Lab
heroSubtitle: Solving critical technology problems for sustained human presence in space
heroOverlayOpacity: 50
heroButtons:
  - label: "Learn More"
    url: "/about"
    style: "primary"
  - label: "Join Our Program"
    url: "/join"
    style: "secondary"
primaryColor: '#b3232f'
primaryColorLight: '#EE2A37'
primaryColorDark: '#7A232F'
accentColor: '#3AB0C8'

# Navigation
navigation:
  - label: "Home"
    url: "/"
    enabled: true
  - label: "About"
    url: "/about"
    enabled: true
  - label: "Students"
    url: "/students"
    enabled: true
  - label: "Research"
    url: "/research"
    enabled: true
  - label: "Resources"
    url: "/resources"
    enabled: true
  - label: "Media"
    url: "/media"
    enabled: true
  - label: "Partners"
    url: "/partners"
    enabled: true
  - label: "Join Us"
    url: "/join"
    enabled: true
  - label: "Contact"
    url: "/contact"
    enabled: true
