heroImage: /images/hero-zerog-research.jpg
heroTitle: Low-Gravity Fluids Lab
heroSubtitle: Solving critical technology problems for sustained human presence in space
heroOverlayOpacity: 50
primaryColor: '#b3232f'
primaryColorLight: '#EE2A37'
primaryColorDark: '#7A232F'
accentColor: '#3AB0C8'
