heroImage: /images/hero-zerog-research.jpg
heroTitle: Space Sciences Lab
heroSubtitle: Solving critical technology problems for sustained human presence in space
heroOverlayOpacity: 50
heroButtons: []
primaryColor: '#b3232f'
primaryColorLight: '#EE2A37'
primaryColorDark: '#7A232F'
accentColor: '#3AB0C8'
navigation:
  - label: Home
    url: /
    enabled: true
  - label: About
    url: /about
    enabled: true
  - label: Students
    url: /students
    enabled: true
  - label: Research
    url: /research
    enabled: true
  - label: Resources
    url: /resources
    enabled: true
  - label: Media
    url: /media
    enabled: true
  - label: Partners
    url: /partners
    enabled: true
  - label: Join
    url: /join
    enabled: false
  - label: Contact
    url: /contact
    enabled: true
introTitle: Latest
introText: TechLeap work continues on acoustic bubble trapping for in-space refueling application.
showFeaturedProjects: true
featuredTitle: Featured Projects
showHighlights: true
highlightsTitle: Program Highlights
highlights:
  - title: Undergraduate Research
    text: Our students compete against graduate programs and aerospace companies, winning recognition including NASA's TechLeap prize.
    buttonText: Meet Our Students
    buttonUrl: /students
  - title: NASA Partnerships
    text: Active NASA-funded programs and collaborations with industry leaders like Blue Origin.
    buttonText: Our Partners
    buttonUrl: /partners
  - title: Real-World Impact
    text: Publishing research, conducting microgravity experiments, and advancing space technology.
    buttonText: View Research
    buttonUrl: /research
showNews: true
newsTitle: Latest News
ctaTitle: Ready to Launch Your Future?
ctaText: Join our team of student researchers working on cutting-edge space technology
ctaButtonText: Apply Now
ctaButtonUrl: /join
